<?php

namespace Database\Seeders;

use App\Models\Destinasi;
use Illuminate\Database\Seeder;

class FotoSeeder extends Seeder
{
    public function run(): void
    {
        $fotos = [
            'Batik Semar Jakarta' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/1c/47/aa/toko-batik-semar-di-bagian.jpg?w=1200&h=-1&s=1',
            'Nasi Uduk Kebon Kacang' => 'https://akcdn.detik.net.id/community/media/visual/2021/02/25/sedapnya-nasi-uduk-kebon-kacang-legendaris-racikan-kedai-zainal-fanani-12.jpeg?w=1280',
            'Masjid Istiqlal' => 'https://upload.wikimedia.org/wikipedia/en/2/25/Masjid_Istiqlal_-_Panoramio.jpg',
            'Soto Betawi H. Ma\'ruf' => 'https://manual.co.id/wp-content/uploads/2018/07/sotohmarufstreet_cikini1.jpg',
            'Galeri Nasional Indonesia' => 'https://salsawisata.com/wp-content/uploads/2022/08/Galeri-Nasional-Indonesia.jpg',
            'Pasar Antik Jl. Surabaya' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/fa/91/6b/pasar-loak-di-jalan-surabaya.jpg?w=1200&h=-1&s=1',
            'Bubur Ayam Senen H. Muhtadi' => 'https://www.reservasiku.com/wp-content/uploads/2023/01/7-Wisata-Kuliner-Bubur-Ayam-Jakarta-Paling-Lezat-Dan-Populer-3.jpeg',
            'Pasar Jatinegara' => 'https://upload.wikimedia.org/wikipedia/commons/5/59/Pasar_Mester_%28Pasar_Regional_Jatinegara%29.jpg',
            'Taman Ismail Marzuki' => 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Plaza_Taman_Ismail_Marzuki.jpg',
            'Museum Nasional Indonesia' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Front_facade_-_National_Museum_Indonesia%2C_Jakarta_%282025%29_-_img_07.jpg',
            'Museum Fatahillah (Museum Sejarah Jakarta)' => 'https://upload.wikimedia.org/wikipedia/commons/5/54/Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg',
            'Museum Bank Indonesia' => 'https://www.jktliving.com/blog/wp-content/uploads/2025/02/Museum-Bank-Indonesia-scaled.jpg',
            'Kawasan Pecinan Glodok' => 'https://awsimages.detik.net.id/community/media/visual/2023/01/21/pecinan-glodok-6_169.jpeg?wid=54&w=1200&v=1&t=jpeg',
            'Cafe Batavia' => 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Cafe_Batavia%2C_Kota_Tua_Jakarta_%282025%29_-_img_01.jpg',
            'Pusat Grosir Tanah Abang' => 'https://salsawisata.com/wp-content/uploads/2023/03/Pusat-Grosir-Metro-Tanah-Abang.jpg',
            'Taman Anggrek Indonesia Permai' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/10/9b/fe/taman-anggrek-indonesia.jpg?w=900&h=-1&s=1',
            'Pasar Santa' => 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Pasar_Santa.jpg',
            'Taman Langsat' => 'https://storage.googleapis.com/seo-cms/assets/Tugu_di_Taman_Langsat_d2ce826cf5/Tugu_di_Taman_Langsat_d2ce826cf5.jpg',
            'Sate Padang Ajo Ramon' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/50/7d/40/sate-padang-ajo-ramon.jpg?w=500&h=-1&s=1',
            'Blok M Square' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/db/05/1d/blok-m-square.jpg?w=900&h=500&s=1',
            'Warung Bu Kris' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/4a/92/af/warung-bu-kris.jpg?w=500&h=-1&s=1',
            'Kebun Raya Bogor' => 'https://upload.wikimedia.org/wikipedia/commons/7/75/Kebun_Raya_Bogor_19.jpg',
            'Roti Unyil Venus Bogor' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/db/e2/0b/roti-unyil-venus.jpg?w=900&h=500&s=1',
            'Soto Kuning Pak Yusuf Bogor' => 'https://journeyofindonesia.com/wp-content/uploads/2023/06/Soto-Kuning-Pak-M-Yusuf-Nuhaa.jpg',
            'Soto Betawi H. Hasan Bekasi' => 'https://petualang.travelingyuk.com/uploads/2020/06/Soto-Betawi-Pak-Hasan-909-944x1024.jpg',
            'Danau Kenanga UI' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Danau_Kenanga_Universitas_Indonesia.jpg/1280px-Danau_Kenanga_Universitas_Indonesia.jpg',
            'Detos (Depok Town Square)' => 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Depok_Town_Square_%28Detos%29_-_panoramio.jpg',
            'Benteng Heritage Museum' => 'https://upload.wikimedia.org/wikipedia/commons/4/42/Benteng_Heritage_Museum_interior.jpg',
            'Pusat Oleh-Oleh Khas Tangerang' => 'https://cove-blog-id.sgp1.cdn.digitaloceanspaces.com/cove-blog-id/2024/05/Oleh-Oleh-Khas-Tangerang.webp',
            'Floating Market Lembang' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/f5/61/b6/kyotoku-floating-market.jpg?w=1200&h=-1&s=1',
            'Batagor Kingsley' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/a2/82/14/batagor-kingsley.jpg?w=1100&h=1100&s=1',
            'Gedung Sate' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Gedung_Sate_Oktober_2024_-_Rahmatdenas.jpg/1280px-Gedung_Sate_Oktober_2024_-_Rahmatdenas.jpg',
            'Surabi Enhaii' => 'https://www.sinergifoundation.org/sinergi/wp-content/uploads/2020/09/surabi-enhaii.jpg',
            'Keraton Kasepuhan Cirebon' => 'https://www.batiqa.com/upload/news/l/cirebon-keraton-kasepuhan_46k7m.jpg',
            'Empal Gentong Krucuk H. Apud' => 'https://empalgentonghapud.shop/public/media/empalgentonghapud-shop/1.jpg',
            'Batik Trusmi' => 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Batik_Trusmi_Cirebon_%2823%29.jpg',
            'Masjid Merah Panjunan' => 'https://upload.wikimedia.org/wikipedia/commons/9/90/Masjid_Panjunan_di_Cirebon%2C_Amerta_-_Berkala_Arkeologi_1%2C_hal._7.jpg',
            'Taman Ade Irma Suryani' => 'https://jejakpiknik.com/wp-content/uploads/2018/02/Informasi-Harga-Tiket-Masuk-Taman-Ade-Irma-Suryani-Cirebon-Waterland-630x380.jpg',
            'Warung Nasi Nini Anteh' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/2e/57/29/kolam-di-nini-anteh.jpg?w=500&h=-1&s=1',
            'Sate Maranggi Banjar' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Makassar/o/1745148140706-sate_maranggi/dyqltqpoitwpuvu.jpeg',
            'Kerajinan Anyaman Rotan Banjar' => 'https://img.antarafoto.com/cache/1200x800/2023/01/26/kerajinan-anyaman-rotan-1407c-dom.jpg',
            'Taman Sari Water Castle' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Tower_in_Taman_Sari%2C_2014-05-19.jpg/1280px-Tower_in_Taman_Sari%2C_2014-05-19.jpg',
            'Gudeg Yu Djum' => 'https://upload.wikimedia.org/wikipedia/id/thumb/9/9a/Gudeg_Yu_Djum.jpg/1280px-Gudeg_Yu_Djum.jpg',
            'Batik Mirota Batik' => 'https://media-cdn.tripadvisor.com/media/photo-s/07/99/8e/7e/mirota-batik.jpg',
            'Sate Klathak Pak Pong' => 'https://assets.telkomsel.com/public/2024-12/Sate-Klathak-Pak-Pong-Kuliner-Legendaris-Yogyakarta.jpg',
            'Desa Wisata Tembi' => 'https://eticon.co.id/wp-content/uploads/2022/07/Desa-wisata-Tembi-Jogja-sumber.jpg',
            'Candi Ratu Boko' => 'https://upload.wikimedia.org/wikipedia/commons/4/48/Keraton_Ratu_Boko_2.jpg',
            'Restoran Bale Raos' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/ce/06/d8/bale-raos.jpg?w=900&h=500&s=1',
            'Gumuk Pasir Parangkusumo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Gumuk_Pasir_Parangkusumo_2.jpg/330px-Gumuk_Pasir_Parangkusumo_2.jpg',
            'Batik Bayat Klaten' => 'https://fitinline.com/data/article/20131102/Batik%20Bayat%20Klaten%201.jpg',
            'Sate Buntel Pak H. Kasdi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/e6/5f/22/sate-buntel-pak-h-kasdi.jpg?w=700&h=400&s=1',
            'Selat Vien\'s' => 'https://selatviens.co.id/data/foto_berita/front.jpg',
            'Pasar Klewer' => 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Pasar_Klewer_Solo.jpg',
            'Museum Batik Danar Hadi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/3f/58/49/museum-batik-danar-hadi.jpg?w=900&h=500&s=1',
            'Pasar Gede Hardjonagoro' => 'https://upload.wikimedia.org/wikipedia/commons/6/61/Pasar_Gede_Harjonagoro.jpg',
            'Nasi Liwet Bu Wongso Lemu' => 'https://goodindonesianfood.com/file/2016/05/solo-classic-nasi-liwet-bu-wongso-lemu-1024x683.jpg',
            'Kawasan Kota Lama Semarang' => 'https://awsimages.detik.net.id/community/media/visual/2023/11/30/kota-lama-semarang_169.jpeg?w=1200',
            'Lawang Sewu' => 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Lawang_sewu_semarang.jpg',
            'Nasi Koyor Kota Lama' => 'https://s3.us-east-1.wasabisys.com/agendaindonesia/2022/10/Nasi-koyor-kota-lama-Semarang-shutterstock.jpeg',
            'Gulai Kambing Bustaman Pak Sabar' => 'https://phinemo.com/wp-content/uploads/2018/03/Gulai-Kambing-Pak-Sabar-Semarang-1024x1024.jpg',
            'Masjid Agung Jawa Tengah' => 'https://static.republika.co.id/uploads/images/xlarge/masjid-agung-jawa-tengah-majt-di-semarang-jateng-foto_230415134338-560.jpg',
            'Kupat Glabed Tegal' => 'https://imgcdn.espos.id/@espos/images/2023/04/Kupat-Glabed-Khas-Tegal.jpg',
            'Taman Pancasila Tegal' => 'https://static.republika.co.id/uploads/images/headline_slide/sejumlah-warga-berada-di-ruang-publik-taman-pancasila-tegal_211028121513-755.jpg',
            'Batik Tegalan Tobal' => 'https://cdn.antaranews.com/cache/1200x800/2019/04/28/perajin-batik-tulis-tegalan-pqo14b-prv.jpg',
            'Museum Batik Pekalongan' => 'https://upload.wikimedia.org/wikipedia/commons/7/73/Pekalongan_Batik_Museum%2C_Central_Java.jpg',
            'Batik Pekalongan Pasar Setono Betek' => 'https://awsimages.detik.net.id/api/wm/2022/05/07/suasana-pasar-batik-setono-kota-pekalongan-sabtu-752022-1_169.jpeg?wid=60&w=1200&v=1&t=jpeg',
            'Taman Andhang Pangrenan' => 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Andhang_pangrenan.jpg',
            'Tugu Pahlawan' => 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Tugu_Pahlawan_Surabaya.jpg',
            'Rujak Cingur Ahmad Jais' => 'https://goodindonesianfood.com/file/2016/05/surabaya-heritage-rujak-cingur-ahmad-jais1-1170x780.jpg',
            'Jembatan Merah' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jembatan_Merah_Surabaya.JPG/960px-Jembatan_Merah_Surabaya.JPG',
            'Soto Ayam Lamongan Cak Har' => 'https://wisato.id/wp-content/uploads/2021/08/Soto-Ayam-Lamongan-Cak-HAR-4-768x432.jpg',
            'House of Sampoerna' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/House_of_Sampoerna_Mei_2015.jpg/1280px-House_of_Sampoerna_Mei_2015.jpg',
            'Taman Bungkul' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/ab/86/c8/taman-bungkul.jpg?w=1200&h=-1&s=1',
            'Rawon Setan Mbak Endang' => 'https://i0.wp.com/www.lintasnusa.id/wp-content/uploads/2021/03/Rawon-Setan-Surabaya-Mbak-Endang-e1507470900676.jpg?fit=800%2C470&ssl=1',
            'Kampung Wisata Peneleh' => 'https://unair.ac.id/wp-content/uploads/2025/01/Kampung-Wisata-Peneleh-Heritage_Pesona-Sejarah-di-Surabaya.png',
            'Lontong Balap Pak Gendut' => 'https://petualang.travelingyuk.com/uploads/2017/05/Lontong-Balap-Pak-Gendut-Surabaya-1024x1024.jpg',
            'Alun-Alun Merdeka Malang' => 'https://malangkota.go.id/wp-content/uploads/2025/08/Alun-Alun-Merdeka-Kota-Malang.jpeg',
            'Malang Strudel' => 'https://nahwatravel.co.id/wp-content/uploads/2023/05/Malang-Strudel-1024x873.jpeg',
            'Pantai Boom Banyuwangi' => 'https://travelspromo.com/wp-content/uploads/2024/09/Suasana-Pantai-Boom-Banyuwangi-640x480.jpg',
            'Sego Tempong Bu Sinar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/1200x0/webp/photo/2023/05/31/sego-tempong-banyuwangi-71710067.jpg',
            'Batik Gajah Oling Banyuwangi' => 'https://metaranews.co/wp-content/uploads/2024/10/batik-gajah-oling.jpg',
            'Candi Penataran' => 'https://upload.wikimedia.org/wikipedia/commons/1/13/Candi_Penataran.jpg',
            'Agrowisata Belimbing Karangsari' => 'https://awsimages.detik.net.id/community/media/visual/2023/06/11/petik-buah-belimbing-di-agrowisata-karangsari-kota-blitar-1_169.jpeg?w=650&q=90',
            'Tahu Kuning Kediri Kak Ana' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Surabaya/f/1758694678537-Gambar_Tahu_Kuning_Khas_Kediri_1/y0heoq7l5g3sv54.jpeg',
            'Monumen Simpang Lima Gumul' => 'https://upload.wikimedia.org/wikipedia/id/c/c1/Monumen_Simpang_Lima_Gumul.jpg',
            'Pecel Madiun Bu Rukmini' => 'https://www.unileverfoodsolutions.co.id/dam/global-ufs/mcos/SEA/calcmenu/recipes/ID-recipes/chicken-&-other-poultry-dishes/pecel-madiun/main-header.jpg',
            'Monumen Kresek' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Monumen_Kresek_Madiun.jpg/1280px-Monumen_Kresek_Madiun.jpg',
            'Sate Ayam Ponorogo Pak Karwo' => 'https://cdn.restaurants-us.com/sateayamponorogopaksibun2madiun/85010-albums-2.jpg',
            'Monumen Nasional (Monas)' => 'https://upload.wikimedia.org/wikipedia/id/b/b1/Merdeka_Square_Monas_02.jpg',
            'Pasar Glodok Elektronik' => 'https://glodokplaza.com/wp-content/uploads/2023/04/Image.webp',
            'Es Krim Ragusa' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Ragusa_Es_Italia_Jalan_Veteran.JPG/960px-Ragusa_Es_Italia_Jalan_Veteran.JPG',
            'Grand Galaxy Park Bekasi' => 'https://cdn-strapi.prod.99iddev.net/assets/Daya_Tarik_Alun_Alun_Bekasi_754b4b4d3e.jpg',
            'Batik Komar' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/83/6e/e7/beautiful-batik-boutique.jpg?w=900&h=500&s=1',
            'Taman Tegalega' => 'https://travelspromo.com/wp-content/uploads/2020/01/08-Taman-Tegallega-Salpa.jpg',
            'Mie Kocok Haji Maman' => 'https://www.harapanrakyat.com/wp-content/uploads/2021/02/18.-Mie-Kocok-Bandung-Legendaris-Citarasa-Khas-Berikut-Rekomendasinya.jpg',
            'Docang Cirebon H. Dadi' => 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Docang.jpg',
            'Kerajinan Payung Geulis Tasikmalaya' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Pembuat_payung_tasik.jpg',
            'Taman Kota Langensari Banjar' => 'https://www.harapanrakyat.com/wp-content/uploads/2019/10/Alun-alun-Langensari-malam-hari-edit.jpg',
            'Candi Prambanan' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Prambanan_Temple_Yogyakarta_Indonesia.jpg',
            'Pasar Beringharjo' => 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Bringharjo_Market_Yogyakarta_-_Pasar_Bringharjo_Jogja_%282025%29_-_img_06.jpg',
            'Bakpia Pathok 25' => 'https://visitingjogja.jogjaprov.go.id/wp-content/uploads/2023/11/bakpia-25-1.jpg',
            'Bakpia Pathok 25 Bantul' => 'https://visitingjogja.jogjaprov.go.id/wp-content/uploads/2023/11/bakpia-25-1.jpg',
            'Candi Plaosan' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Plaosan_Temple.jpg/1280px-Plaosan_Temple.jpg',
            'Candi Prambanan (Gerbang Klaten)' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Prambanan_Temple_Yogyakarta_Indonesia.jpg',
            'Warung Soto Klaten Pak Marto' => 'https://ik.trn.asia/uploads/2020/02/pak-marto-1.jpg',
            'Pura Mangkunegaran' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Grand_Pendopo%2C_Mangkunegaran_Palace.jpg/960px-Grand_Pendopo%2C_Mangkunegaran_Palace.jpg',
            'Semarang Kreatif Galeri' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Sam_Po_Kong_Temple_Semarang_Indonesia.jpg/1280px-Sam_Po_Kong_Temple_Semarang_Indonesia.jpg',
            'Sego Megono Mbah Ibah' => 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Nasi_megono.JPG',
            'Sroto Sokaraja Pak Bambang' => 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Getuk_goreng_Sokaraja.jpg',
            'Rawon Rampal' => 'https://malangkota.go.id/wp-content/uploads/2021/04/rawon2-1.jpeg',
            'Jalan Ijen Boulevard' => 'https://tugumalang.id/wp-content/uploads/2022/01/ijen.jpg',
            'Gudeg Lumintu Jember' => 'https://ik.imagekit.io/tvlk/blog/2025/06/Sekilas-Tentang-Alun-Alun-Jember.jpg?tr=q-70,c-at_max,w-1000,h-600',
            'Pecel Blitar Bu Tri' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pecel_Hariadhi.JPG/1280px-Pecel_Hariadhi.JPG',
            'Nasi Kapau Uni Lis' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/98/82/79/20180408-152334-largejpg.jpg?w=900&h=500&s=1',
            'Mie Ayam Bangka Amat Jatinegara' => 'https://asset.kompas.com/crops/JlIAFTMi-vQFrQvAXqDjOOIHNkY=/0x0:0x0/1200x800/data/photo/2022/09/23/632d7f2048c24.jpg',
            'Bakmi Gang Kelinci' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/90/1672835768-IMG-20230104-WA0008.jpg',
            'Alun-Alun Kota Bekasi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/b3/a0/4d/img-20180714-175437-largejpg.jpg?w=1200&h=-1&s=1',
            'Mie Ayam Bangka 99 Margonda' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/6ccd8cb8-f24e-4a49-988c-13c8315c402c_Go-Biz_20241223_123444.jpeg',
            'Pasar Lama Tangerang' => 'https://asset.kompas.com/crops/gjrbGNgm7RHLoM-wdS46zhJ3YK4=/0x0:3510x2340/1200x1200/data/photo/2023/01/14/63c2203063d31.jpg',
            'Laksa Tangerang Encim Gerot' => 'https://asset.kompas.com/crops/daXuN9o98DyqTXoJjQsznpd_gXU=/0x0:1000x667/750x500/data/photo/2022/07/24/62dcb82f1eedc.jpeg',
            'Pasar Kosambi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/b7/e2/21/img20180706181948-largejpg.jpg?w=1200&h=-1&s=1',
            'Sate Kambing Pak H. Yusuf' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/42/35/db/photo1jpg.jpg?w=1200&h=-1&s=1',
            'Kampung Adat Cikondang' => 'https://cdn.antaranews.com/cache/1200x800/2023/02/12/IMG-20230212-WA0036.jpg.webp',
            'Nasi Jamblang Ibu Nur' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/fa/a8/25/caption.jpg?w=1200&h=1200&s=1',
            'Kupat Tahu Kabita' => 'https://www.garnesia.com/images/vendor/5267_d8bf6c2518d02a55199d2112b933b0ad.jpg',
            'Situ Gede Tasikmalaya' => 'https://asset.kompas.com/crops/wnEcakCY2uxHBCIa-2-WjqL2GTo=/63x11:934x591/1200x675/data/photo/2020/08/18/5f3b8dbe49549.jpg',
            'Keraton Ngayogyakarta Hadiningrat' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Jogja_-_Kraton_Yogyakarta_-_Donopratono_gate_%282025%29_-_img_02.jpg',
            'Angkringan Lik Man' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/3d/84/c1/img-20190907-203237-largejpg.jpg?w=900&h=-1&s=1',
            'Pantai Parangtritis' => 'https://asset.kompas.com/crops/bLvlkxxPDoC4oRDfY0Vh6HkROTU=/0x0:739x493/1200x800/data/photo/2021/03/07/6044b67dc51f5.jpg',
            'Keraton Kasunanan Surakarta' => 'https://asset.kompas.com/crops/gls85oCrHSDR1vl5Huz3bDeb5H8=/0x0:1200x800/1200x800/data/photo/2024/12/04/674fc46fddfa7.jpg',
            'Klenteng Sam Poo Kong' => 'https://asset.kompas.com/crops/MG-Mkx0c0RIAssO8B0MrK_hBonQ=/0x0:0x0/1200x900/data/photo/2022/09/09/631b186871610.jpg',
            'Lumpia Gang Lombok' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/7f/be/ff/fasad-depan.jpg?w=1200&h=-1&s=1',
            'Sate Blengong Tegal Bu Hj. Darmi' => 'https://visitjawatengah.jatengprov.go.id/assets/images/116410c9-d101-4d83-90af-0cc334a5e293.jpeg',
            'Pindang Tetel Pak Darsono' => 'https://visitjawatengah.jatengprov.go.id/assets/images/fe361522-9427-41d7-994a-4de382cb1a45.jpg',
            'Objek Wisata Baturaden' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Baturraden_overview_from_ridge%2C_Purwokerto%2C_2015-03-23.jpg',
            'Pusat Kuliner Pratistha Hasta' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/a64ba7a9-fa24-4884-bacc-7f5d42204b24_Go-Biz_20210308_080021.jpeg',
            'Getuk Goreng Sokaraja Haji Tohirin' => 'https://cdn.idntimes.com/content-images/community/2021/11/fromandroid-90684dabe82dc996721afa6c03d58c74.jpg',
            'Pasar Atom' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/54/92/15/caption.jpg?w=1200&h=-1&s=1',
            'Bakso Cak Toha' => 'https://itin-dev.wanderlogstatic.com/freeImage/OyUVayqyJ9nx2xdYrMZ3zXDSOSuL7Vw5',
            'Alun-Alun Jember' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Suwar-suwir_Sari_Rasa.jpg/1280px-Suwar-suwir_Sari_Rasa.jpg',
            'Suwar-Suwir Jember Bu Mie' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/fd/a8/c2/20190620-101204-largejpg.jpg?w=900&h=500&s=1',
            'Warung Bu Darum' => null,
            'Kawah Ijen' => 'https://asset.kompas.com/crops/NwUxznt2nYwzDRPdEBOpXkkIUj4=/39x0:573x356/750x500/data/photo/2019/07/19/5d317cc27b36e.jpeg',
            'Makam Bung Karno' => 'https://asset.kompas.com/crops/MmVyWwNwt_wv0A0JMgLe3fRqH_A=/0x2:1024x684/1200x900/data/photo/2023/05/14/64606982782dc.jpeg',
            'Goa Selomangleng' => 'https://assets.promediateknologi.com/crop/0x0:0x0/x/photo/2022/09/08/1636026740.jpg',
            'Soto Ayam Kampung Kediri Pak Sabar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/1200x0/webp/photo/2023/02/06/1282199188.jpeg',
            'Brem Madiun Sido Maju' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Telaga_Sarangan_dan_Gunung_Lawu_-_Maret_2026.jpg/1280px-Telaga_Sarangan_dan_Gunung_Lawu_-_Maret_2026.jpg',
        ];

        $updated = 0;
        foreach ($fotos as $nama => $foto) {
            $rows = Destinasi::where('nama', $nama)->update(['foto' => $foto]);
            $updated += $rows;
        }
        $this->command->info("Updated foto for {$updated} destinasi.");
    }
}
