<?php

namespace Database\Seeders;

use App\Models\Destinasi;
use Illuminate\Database\Seeder;

class FotoSeeder extends Seeder
{
    public function run(): void
    {
        $fotos = [
            'Batik Semar Jakarta' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/1c/47/aa/toko-batik-semar-di-bagian.jpg?w=1200&h=-1&s=1',
            'Nasi Uduk Kebon Kacang' => 'https://akcdn.detik.net.id/community/media/visual/2021/02/25/sedapnya-nasi-uduk-kebon-kacang-legendaris-racikan-kedai-zainal-fanani-12.jpeg?w=1280',
            'Masjid Istiqlal' => 'https://upload.wikimedia.org/wikipedia/en/2/25/Masjid_Istiqlal_-_Panoramio.jpg',
            'Galeri Nasional Indonesia' => 'https://salsawisata.com/wp-content/uploads/2022/08/Galeri-Nasional-Indonesia.jpg',
            'Pasar Antik Jl. Surabaya' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/fa/91/6b/pasar-loak-di-jalan-surabaya.jpg?w=1200&h=-1&s=1',
            'Bubur Ayam Senen H. Muhtadi' => 'https://www.reservasiku.com/wp-content/uploads/2023/01/7-Wisata-Kuliner-Bubur-Ayam-Jakarta-Paling-Lezat-Dan-Populer-3.jpeg',
            'Pasar Jatinegara' => 'https://upload.wikimedia.org/wikipedia/commons/5/59/Pasar_Mester_%28Pasar_Regional_Jatinegara%29.jpg',
            'Taman Ismail Marzuki' => 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Plaza_Taman_Ismail_Marzuki.jpg',
            'Museum Nasional Indonesia' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Front_facade_-_National_Museum_Indonesia%2C_Jakarta_%282025%29_-_img_07.jpg',
            'Museum Fatahillah (Museum Sejarah Jakarta)' => 'https://upload.wikimedia.org/wikipedia/commons/5/54/Batavia_City_Hall_%28Jakarta_History_Museum%29_Fatahillah_Square_%282025%29_-_img_03.jpg',
            'Museum Bank Indonesia' => 'https://www.jktliving.com/blog/wp-content/uploads/2025/02/Museum-Bank-Indonesia-scaled.jpg',
            'Kawasan Pecinan Glodok' => 'https://awsimages.detik.net.id/community/media/visual/2023/01/21/pecinan-glodok-6_169.jpeg?wid=54&w=1200&v=1&t=jpeg',
            'Cafe Batavia' => 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Cafe_Batavia%2C_Kota_Tua_Jakarta_%282025%29_-_img_01.jpg',
            'Pusat Grosir Tanah Abang' => 'https://salsawisata.com/wp-content/uploads/2023/03/Pusat-Grosir-Metro-Tanah-Abang.jpg',
            'Taman Anggrek Indonesia Permai' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/10/9b/fe/taman-anggrek-indonesia.jpg?w=900&h=-1&s=1',
            'Pasar Santa' => 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Pasar_Santa.jpg',
            'Taman Langsat' => 'https://storage.googleapis.com/seo-cms/assets/Tugu_di_Taman_Langsat_d2ce826cf5/Tugu_di_Taman_Langsat_d2ce826cf5.jpg',
            'Sate Padang Ajo Ramon' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/50/7d/40/sate-padang-ajo-ramon.jpg?w=500&h=-1&s=1',
            'Blok M Square' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/db/05/1d/blok-m-square.jpg?w=900&h=500&s=1',
            'Warung Bu Kris' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/4a/92/af/warung-bu-kris.jpg?w=500&h=-1&s=1',
            'Kebun Raya Bogor' => 'https://upload.wikimedia.org/wikipedia/commons/7/75/Kebun_Raya_Bogor_19.jpg',
            'Roti Unyil Venus Bogor' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/db/e2/0b/roti-unyil-venus.jpg?w=900&h=500&s=1',
            'Soto Kuning Pak Yusuf Bogor' => 'https://journeyofindonesia.com/wp-content/uploads/2023/06/Soto-Kuning-Pak-M-Yusuf-Nuhaa.jpg',
            'Alun-Alun Kota Bekasi' => 'https://cdn-strapi.prod.99iddev.net/assets/Daya_Tarik_Alun_Alun_Bekasi_754b4b4d3e.jpg',
            'Soto Betawi H. Hasan Bekasi' => 'https://petualang.travelingyuk.com/uploads/2020/06/Soto-Betawi-Pak-Hasan-909-944x1024.jpg',
            'Danau Kenanga UI' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Danau_Kenanga_Universitas_Indonesia.jpg/1280px-Danau_Kenanga_Universitas_Indonesia.jpg',
            'Detos (Depok Town Square)' => 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Depok_Town_Square_%28Detos%29_-_panoramio.jpg',
            'Benteng Heritage Museum' => 'https://upload.wikimedia.org/wikipedia/commons/4/42/Benteng_Heritage_Museum_interior.jpg',
            'Pusat Oleh-Oleh Khas Tangerang' => 'https://cove-blog-id.sgp1.cdn.digitaloceanspaces.com/cove-blog-id/2024/05/Oleh-Oleh-Khas-Tangerang.webp',
            'Floating Market Lembang' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/f5/61/b6/kyotoku-floating-market.jpg?w=1200&h=-1&s=1',
            'Batagor Kingsley' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/a2/82/14/batagor-kingsley.jpg?w=1100&h=1100&s=1',
            'Gedung Sate' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Gedung_Sate_Oktober_2024_-_Rahmatdenas.jpg/1280px-Gedung_Sate_Oktober_2024_-_Rahmatdenas.jpg',
            'Surabi Enhaii' => 'https://www.sinergifoundation.org/sinergi/wp-content/uploads/2020/09/surabi-enhaii.jpg',
            'Keraton Kasepuhan Cirebon' => 'https://www.batiqa.com/upload/news/l/cirebon-keraton-kasepuhan_46k7m.jpg',
            'Empal Gentong Krucuk H. Apud' => 'https://empalgentonghapud.shop/public/media/empalgentonghapud-shop/1.jpg',
            'Batik Trusmi' => 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Batik_Trusmi_Cirebon_%2823%29.jpg',
            'Masjid Merah Panjunan' => 'https://upload.wikimedia.org/wikipedia/commons/9/90/Masjid_Panjunan_di_Cirebon%2C_Amerta_-_Berkala_Arkeologi_1%2C_hal._7.jpg',
            'Taman Ade Irma Suryani' => 'https://jejakpiknik.com/wp-content/uploads/2018/02/Informasi-Harga-Tiket-Masuk-Taman-Ade-Irma-Suryani-Cirebon-Waterland-630x380.jpg',
            'Warung Nasi Nini Anteh' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/2e/57/29/kolam-di-nini-anteh.jpg?w=500&h=-1&s=1',
            'Sate Maranggi Banjar' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Makassar/o/1745148140706-sate_maranggi/dyqltqpoitwpuvu.jpeg',
            'Kerajinan Anyaman Rotan Banjar' => 'https://img.antarafoto.com/cache/1200x800/2023/01/26/kerajinan-anyaman-rotan-1407c-dom.jpg',
            'Taman Sari Water Castle' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Tower_in_Taman_Sari%2C_2014-05-19.jpg/1280px-Tower_in_Taman_Sari%2C_2014-05-19.jpg',
            'Gudeg Yu Djum' => 'https://upload.wikimedia.org/wikipedia/id/thumb/9/9a/Gudeg_Yu_Djum.jpg/1280px-Gudeg_Yu_Djum.jpg',
            'Batik Mirota Batik' => 'https://media-cdn.tripadvisor.com/media/photo-s/07/99/8e/7e/mirota-batik.jpg',
            'Sate Klathak Pak Pong' => 'https://assets.telkomsel.com/public/2024-12/Sate-Klathak-Pak-Pong-Kuliner-Legendaris-Yogyakarta.jpg',
            'Desa Wisata Tembi' => 'https://eticon.co.id/wp-content/uploads/2022/07/Desa-wisata-Tembi-Jogja-sumber.jpg',
            'Candi Ratu Boko' => 'https://upload.wikimedia.org/wikipedia/commons/4/48/Keraton_Ratu_Boko_2.jpg',
            'Restoran Bale Raos' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/ce/06/d8/bale-raos.jpg?w=900&h=500&s=1',
            'Gumuk Pasir Parangkusumo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Gumuk_Pasir_Parangkusumo_2.jpg/330px-Gumuk_Pasir_Parangkusumo_2.jpg',
            'Batik Bayat Klaten' => 'https://fitinline.com/data/article/20131102/Batik%20Bayat%20Klaten%201.jpg',
            'Sate Buntel Pak H. Kasdi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/e6/5f/22/sate-buntel-pak-h-kasdi.jpg?w=700&h=400&s=1',
            'Selat Vien\'s' => 'https://selatviens.co.id/data/foto_berita/front.jpg',
            'Pasar Klewer' => 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Pasar_Klewer_Solo.jpg',
            'Museum Batik Danar Hadi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/3f/58/49/museum-batik-danar-hadi.jpg?w=900&h=500&s=1',
            'Pasar Gede Hardjonagoro' => 'https://upload.wikimedia.org/wikipedia/commons/6/61/Pasar_Gede_Harjonagoro.jpg',
            'Nasi Liwet Bu Wongso Lemu' => 'https://goodindonesianfood.com/file/2016/05/solo-classic-nasi-liwet-bu-wongso-lemu-1024x683.jpg',
            'Kawasan Kota Lama Semarang' => 'https://awsimages.detik.net.id/community/media/visual/2023/11/30/kota-lama-semarang_169.jpeg?w=1200',
            'Lawang Sewu' => 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Lawang_sewu_semarang.jpg',
            'Nasi Koyor Kota Lama' => 'https://s3.us-east-1.wasabisys.com/agendaindonesia/2022/10/Nasi-koyor-kota-lama-Semarang-shutterstock.jpeg',
            'Gulai Kambing Bustaman Pak Sabar' => 'https://phinemo.com/wp-content/uploads/2018/03/Gulai-Kambing-Pak-Sabar-Semarang-1024x1024.jpg',
            'Masjid Agung Jawa Tengah' => 'https://static.republika.co.id/uploads/images/xlarge/masjid-agung-jawa-tengah-majt-di-semarang-jateng-foto_230415134338-560.jpg',
            'Kupat Glabed Tegal' => 'https://imgcdn.espos.id/@espos/images/2023/04/Kupat-Glabed-Khas-Tegal.jpg',
            'Taman Pancasila Tegal' => 'https://static.republika.co.id/uploads/images/headline_slide/sejumlah-warga-berada-di-ruang-publik-taman-pancasila-tegal_211028121513-755.jpg',
            'Batik Tegalan Tobal' => 'https://cdn.antaranews.com/cache/1200x800/2019/04/28/perajin-batik-tulis-tegalan-pqo14b-prv.jpg',
            'Museum Batik Pekalongan' => 'https://upload.wikimedia.org/wikipedia/commons/7/73/Pekalongan_Batik_Museum%2C_Central_Java.jpg',
            'Batik Pekalongan Pasar Setono Betek' => 'https://awsimages.detik.net.id/api/wm/2022/05/07/suasana-pasar-batik-setono-kota-pekalongan-sabtu-752022-1_169.jpeg?wid=60&w=1200&v=1&t=jpeg',
            'Taman Andhang Pangrenan' => 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Andhang_pangrenan.jpg',
            'Tugu Pahlawan' => 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Tugu_Pahlawan_Surabaya.jpg',
            'Rujak Cingur Ahmad Jais' => 'https://goodindonesianfood.com/file/2016/05/surabaya-heritage-rujak-cingur-ahmad-jais1-1170x780.jpg',
            'Jembatan Merah' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jembatan_Merah_Surabaya.JPG/960px-Jembatan_Merah_Surabaya.JPG',
            'Soto Ayam Lamongan Cak Har' => 'https://wisato.id/wp-content/uploads/2021/08/Soto-Ayam-Lamongan-Cak-HAR-4-768x432.jpg',
            'House of Sampoerna' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/House_of_Sampoerna_Mei_2015.jpg/1280px-House_of_Sampoerna_Mei_2015.jpg',
            'Taman Bungkul' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/ab/86/c8/taman-bungkul.jpg?w=1200&h=-1&s=1',
            'Rawon Setan Mbak Endang' => 'https://i0.wp.com/www.lintasnusa.id/wp-content/uploads/2021/03/Rawon-Setan-Surabaya-Mbak-Endang-e1507470900676.jpg?fit=800%2C470&ssl=1',
            'Kampung Wisata Peneleh' => 'https://unair.ac.id/wp-content/uploads/2025/01/Kampung-Wisata-Peneleh-Heritage_Pesona-Sejarah-di-Surabaya.png',
            'Lontong Balap Pak Gendut' => 'https://petualang.travelingyuk.com/uploads/2017/05/Lontong-Balap-Pak-Gendut-Surabaya-1024x1024.jpg',
            'Alun-Alun Merdeka Malang' => 'https://malangkota.go.id/wp-content/uploads/2025/08/Alun-Alun-Merdeka-Kota-Malang.jpeg',
            'Malang Strudel' => 'https://nahwatravel.co.id/wp-content/uploads/2023/05/Malang-Strudel-1024x873.jpeg',
            'Alun-Alun Jember' => 'https://ik.imagekit.io/tvlk/blog/2025/06/Sekilas-Tentang-Alun-Alun-Jember.jpg?tr=q-70,c-at_max,w-1000,h-600',
            'Suwar-Suwir Jember Bu Mie' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Suwar-suwir_Sari_Rasa.jpg/1280px-Suwar-suwir_Sari_Rasa.jpg',
            'Pantai Boom Banyuwangi' => 'https://travelspromo.com/wp-content/uploads/2024/09/Suasana-Pantai-Boom-Banyuwangi-640x480.jpg',
            'Sego Tempong Bu Sinar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/1200x0/webp/photo/2023/05/31/sego-tempong-banyuwangi-71710067.jpg',
            'Batik Gajah Oling Banyuwangi' => 'https://metaranews.co/wp-content/uploads/2024/10/batik-gajah-oling.jpg',
            'Candi Penataran' => 'https://upload.wikimedia.org/wikipedia/commons/1/13/Candi_Penataran.jpg',
            'Agrowisata Belimbing Karangsari' => 'https://awsimages.detik.net.id/community/media/visual/2023/06/11/petik-buah-belimbing-di-agrowisata-karangsari-kota-blitar-1_169.jpeg?w=650&q=90',
            'Tahu Kuning Kediri Kak Ana' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Surabaya/f/1758694678537-Gambar_Tahu_Kuning_Khas_Kediri_1/y0heoq7l5g3sv54.jpeg',
            'Monumen Simpang Lima Gumul' => 'https://upload.wikimedia.org/wikipedia/id/c/c1/Monumen_Simpang_Lima_Gumul.jpg',
            'Pecel Madiun Bu Rukmini' => 'https://www.unileverfoodsolutions.co.id/dam/global-ufs/mcos/SEA/calcmenu/recipes/ID-recipes/chicken-&-other-poultry-dishes/pecel-madiun/main-header.jpg',
            'Monumen Kresek' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Monumen_Kresek_Madiun.jpg/1280px-Monumen_Kresek_Madiun.jpg',
            'Sate Ayam Ponorogo Pak Karwo' => 'https://cdn.restaurants-us.com/sateayamponorogopaksibun2madiun/85010-albums-2.jpg',
            'Soto Betawi H. Ma\'ruf' => 'https://manual.co.id/wp-content/uploads/2018/07/sotohmarufstreet_cikini1.jpg',
            'Monumen Nasional (Monas)' => 'https://upload.wikimedia.org/wikipedia/id/b/b1/Merdeka_Square_Monas_02.jpg',
            'Pasar Glodok Elektronik' => 'https://glodokplaza.com/wp-content/uploads/2023/04/Image.webp',
            'Es Krim Ragusa' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Ragusa_Es_Italia_Jalan_Veteran.JPG/960px-Ragusa_Es_Italia_Jalan_Veteran.JPG',
            'Batik Komar' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/83/6e/e7/beautiful-batik-boutique.jpg?w=900&h=500&s=1',
            'Taman Tegalega' => 'https://travelspromo.com/wp-content/uploads/2020/01/08-Taman-Tegallega-Salpa.jpg',
            'Mie Kocok Haji Maman' => 'https://www.harapanrakyat.com/wp-content/uploads/2021/02/18.-Mie-Kocok-Bandung-Legendaris-Citarasa-Khas-Berikut-Rekomendasinya.jpg',
            'Docang Cirebon H. Dadi' => 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Docang.jpg',
            'Kerajinan Payung Geulis Tasikmalaya' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Pembuat_payung_tasik.jpg',
            'Taman Kota Langensari Banjar' => 'https://www.harapanrakyat.com/wp-content/uploads/2019/10/Alun-alun-Langensari-malam-hari-edit.jpg',
            'Candi Prambanan' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Prambanan_Temple_Yogyakarta_Indonesia.jpg',
            'Pasar Beringharjo' => 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Bringharjo_Market_Yogyakarta_-_Pasar_Bringharjo_Jogja_%282025%29_-_img_06.jpg',
            'Bakpia Pathok 25' => 'https://visitingjogja.jogjaprov.go.id/wp-content/uploads/2023/11/bakpia-25-1.jpg',
            'Bakpia Pathok 25 Bantul' => 'https://visitingjogja.jogjaprov.go.id/wp-content/uploads/2023/11/bakpia-25-1.jpg',
            'Candi Plaosan' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Plaosan_Temple.jpg/1280px-Plaosan_Temple.jpg',
            'Candi Prambanan (Gerbang Klaten)' => 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Prambanan_Temple_Yogyakarta_Indonesia.jpg',
            'Warung Soto Klaten Pak Marto' => 'https://ik.trn.asia/uploads/2020/02/pak-marto-1.jpg',
            'Pura Mangkunegaran' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Grand_Pendopo%2C_Mangkunegaran_Palace.jpg/960px-Grand_Pendopo%2C_Mangkunegaran_Palace.jpg',
            'Semarang Kreatif Galeri' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Sam_Po_Kong_Temple_Semarang_Indonesia.jpg/1280px-Sam_Po_Kong_Temple_Semarang_Indonesia.jpg',
            'Sego Megono Mbah Ibah' => 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Nasi_megono.JPG',
            'Sroto Sokaraja Pak Bambang' => 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Getuk_goreng_Sokaraja.jpg',
            'Rawon Rampal' => 'https://malangkota.go.id/wp-content/uploads/2021/04/rawon2-1.jpeg',
            'Jalan Ijen Boulevard' => 'https://tugumalang.id/wp-content/uploads/2022/01/ijen.jpg',
            'Pecel Blitar Bu Tri' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Pecel_Hariadhi.JPG/1280px-Pecel_Hariadhi.JPG',
            'Nasi Kapau Uni Lis' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/98/82/79/20180408-152334-largejpg.jpg?w=900&h=500&s=1',
            'Mie Ayam Bangka Amat Jatinegara' => 'https://asset.kompas.com/crops/JlIAFTMi-vQFrQvAXqDjOOIHNkY=/0x0:0x0/1200x800/data/photo/2022/09/23/632d7f2048c24.jpg',
            'Bakmi Gang Kelinci' => 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/90/1672835768-IMG-20230104-WA0008.jpg',
            'Grand Galaxy Park Bekasi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/b3/a0/4d/img-20180714-175437-largejpg.jpg?w=1200&h=-1&s=1',
            'Mie Ayam Bangka 99 Margonda' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/6ccd8cb8-f24e-4a49-988c-13c8315c402c_Go-Biz_20241223_123444.jpeg',
            'Pasar Lama Tangerang' => 'https://asset.kompas.com/crops/gjrbGNgm7RHLoM-wdS46zhJ3YK4=/0x0:3510x2340/1200x1200/data/photo/2023/01/14/63c2203063d31.jpg',
            'Laksa Tangerang Encim Gerot' => 'https://asset.kompas.com/crops/daXuN9o98DyqTXoJjQsznpd_gXU=/0x0:1000x667/750x500/data/photo/2022/07/24/62dcb82f1eedc.jpeg',
            'Pasar Kosambi' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/b7/e2/21/img20180706181948-largejpg.jpg?w=1200&h=-1&s=1',
            'Sate Kambing Pak H. Yusuf' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/42/35/db/photo1jpg.jpg?w=1200&h=-1&s=1',
            'Kampung Adat Cikondang' => 'https://cdn.antaranews.com/cache/1200x800/2023/02/12/IMG-20230212-WA0036.jpg.webp',
            'Nasi Jamblang Ibu Nur' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/fa/a8/25/caption.jpg?w=1200&h=1200&s=1',
            'Kupat Tahu Kabita' => 'https://www.garnesia.com/images/vendor/5267_d8bf6c2518d02a55199d2112b933b0ad.jpg',
            'Situ Gede Tasikmalaya' => 'https://asset.kompas.com/crops/wnEcakCY2uxHBCIa-2-WjqL2GTo=/63x11:934x591/1200x675/data/photo/2020/08/18/5f3b8dbe49549.jpg',
            'Keraton Ngayogyakarta Hadiningrat' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Jogja_-_Kraton_Yogyakarta_-_Donopratono_gate_%282025%29_-_img_02.jpg',
            'Angkringan Lik Man' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/3d/84/c1/img-20190907-203237-largejpg.jpg?w=900&h=-1&s=1',
            'Pantai Parangtritis' => 'https://asset.kompas.com/crops/bLvlkxxPDoC4oRDfY0Vh6HkROTU=/0x0:739x493/1200x800/data/photo/2021/03/07/6044b67dc51f5.jpg',
            'Keraton Kasunanan Surakarta' => 'https://asset.kompas.com/crops/gls85oCrHSDR1vl5Huz3bDeb5H8=/0x0:1200x800/1200x800/data/photo/2024/12/04/674fc46fddfa7.jpg',
            'Klenteng Sam Poo Kong' => 'https://asset.kompas.com/crops/MG-Mkx0c0RIAssO8B0MrK_hBonQ=/0x0:0x0/1200x900/data/photo/2022/09/09/631b186871610.jpg',
            'Lumpia Gang Lombok' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/7f/be/ff/fasad-depan.jpg?w=1200&h=-1&s=1',
            'Sate Blengong Tegal Bu Hj. Darmi' => 'https://visitjawatengah.jatengprov.go.id/assets/images/116410c9-d101-4d83-90af-0cc334a5e293.jpeg',
            'Pindang Tetel Pak Darsono' => 'https://visitjawatengah.jatengprov.go.id/assets/images/fe361522-9427-41d7-994a-4de382cb1a45.jpg',
            'Objek Wisata Baturaden' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Baturraden_overview_from_ridge%2C_Purwokerto%2C_2015-03-23.jpg',
            'Pusat Kuliner Pratistha Hasta' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/a64ba7a9-fa24-4884-bacc-7f5d42204b24_Go-Biz_20210308_080021.jpeg',
            'Getuk Goreng Sokaraja Haji Tohirin' => 'https://cdn.idntimes.com/content-images/community/2021/11/fromandroid-90684dabe82dc996721afa6c03d58c74.jpg',
            'Pasar Atom' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/54/92/15/caption.jpg?w=1200&h=-1&s=1',
            'Bakso Cak Toha' => 'https://itin-dev.wanderlogstatic.com/freeImage/OyUVayqyJ9nx2xdYrMZ3zXDSOSuL7Vw5',
            'Gudeg Lumintu Jember' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/fd/a8/c2/20190620-101204-largejpg.jpg?w=900&h=500&s=1',
            'Warung Bu Darum' => null,
            'Kawah Ijen' => 'https://asset.kompas.com/crops/NwUxznt2nYwzDRPdEBOpXkkIUj4=/39x0:573x356/750x500/data/photo/2019/07/19/5d317cc27b36e.jpeg',
            'Makam Bung Karno' => 'https://asset.kompas.com/crops/MmVyWwNwt_wv0A0JMgLe3fRqH_A=/0x2:1024x684/1200x900/data/photo/2023/05/14/64606982782dc.jpeg',
            'Goa Selomangleng' => 'https://assets.promediateknologi.com/crop/0x0:0x0/x/photo/2022/09/08/1636026740.jpg',
            'Soto Ayam Kampung Kediri Pak Sabar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/1200x0/webp/photo/2023/02/06/1282199188.jpeg',
            'Brem Madiun Sido Maju' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Telaga_Sarangan_dan_Gunung_Lawu_-_Maret_2026.jpg/1280px-Telaga_Sarangan_dan_Gunung_Lawu_-_Maret_2026.jpg',
            'Situ Ciburuy' => 'https://awsimages.detik.net.id/community/media/visual/2022/08/13/wajah-baru-situ-ciburuy-bandung-barat_169.jpeg?w=600&q=90',
            'Curug Cimahi (Curug Pelangi)' => 'https://img.antarafoto.com/cache/1200x800/2024/10/27/potensi-pariwisata-curug-pelangi-cimahi-1elgh-dom.jpg',
            'Taman Bunga Nusantara' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/fb/be/a5/taman-bunga-nusantara.jpg?w=1200&h=-1&s=1',
            'Sate Maranggi Cibungur' => 'https://cairofood.id/wp-content/uploads/sate-maranggi-cibungur-cairo-1067x800.jpg',
            'Beras Pandanwangi Cianjur' => 'https://infocianjur.com/wp-content/uploads/2019/02/BERAS-PANDANWANGI.jpg',
            'Geopark Ciletuh UNESCO' => 'https://upload.wikimedia.org/wikipedia/commons/5/53/Curug_Cimarinjung%2C_Geopark_Ciletuh%2C_Ciemas%2C_Sukabumi%2C_Jawa_Barat_0607201602.jpg',
            'Pantai Pelabuhan Ratu' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Panorama_Pantai_Pelabuhan_Ratu_Sukabumi.jpg/1280px-Panorama_Pantai_Pelabuhan_Ratu_Sukabumi.jpg',
            'Mochi Sukabumi Lampion' => 'https://static.vecteezy.com/system/resources/previews/008/199/253/large_2x/mochi-lampion-sukabumi-chewy-rice-cake-on-bamboo-packaging-photo.jpg',
            'Makam Syekh Quro Karawang' => 'https://s3-ap-southeast-1.amazonaws.com/cntatr-assets-ap-southeast-1-250226768838-55a62c9399d4d8a6/2025/03/Makam-Syekh-Quro-1024x682.jpeg?tr=q-70,c-at_max,w-1000,h-600',
            'Opak Ketan Karawang' => 'https://www.gotravelly.com/blog/wp-content/uploads/2022/07/opak-ketan.jpg',
            'Mangga Gedong Gincu Indramayu' => 'https://beritaindramayu.com/wp-content/uploads/2025/10/061025-Mangga-gedong-gincu.jpg',
            'Pantai Karangsong Indramayu' => 'https://upload.wikimedia.org/wikipedia/commons/4/48/Karangsong_beach_in_Indramayu%2C_West_Java.jpg',
            'Situs Galuh Purba Ciamis' => 'https://cdns.klimg.com/merdeka.com/i/w/news/2013/08/02/229961/540x270/melongok-jejak-kerajaan-galuh-purba-dan-legenda-ciung-wanara-survei-jalur-mudik-15.jpg',
            'Perkebunan Nanas Subang' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhlllMfxQYl9rdTxZw3MRJ4-ZcI5x9pB6mFf0m901a9dY-471j8DA1dZCD8DeM8mJdFKBnp3G0QGIxJ6I0F-Vv3hnghtqI0kjaxuahcCLx04gducYzWEDwX1GW1uZr3XMnb9jf_aqg2f0/w1200-h630-p-k-no-nu/nanas+si+madu+subang+(2).jpg',
            'Sate Maranggi Subang' => 'https://awsimages.detik.net.id/api/wm/2022/07/25/sate-maranggi-tata-di-subang_169.jpeg?wid=54&w=1200&v=1&t=jpeg',
            'Sate Kambing H. Abdullah Sudirman' => 'https://awsimages.detik.net.id/community/media/visual/2021/07/21/sate-kambing_169.jpeg?w=1200',
            'Taman Suropati Menteng' => 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Taman_Suropati.JPG',
            'Pasar Tanah Abang' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/81/8b/68/tanah-abang-market.jpg?w=1200&h=-1&s=1',
            'Taman Mini Indonesia Indah (TMII)' => 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Istana_Anak-anak_Indonesia_TMII_%282025%29_-_img_01.jpg',
            'BSD City & AEON Mall' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/c1/c9/e4/aeon-mall-bsd-city.jpg?w=1200&h=-1&s=1',
            'Situ Gintung' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Situ_Gintung_2014.jpg/1280px-Situ_Gintung_2014.jpg',
            'Situs Banten Lama' => 'https://www.indonesia.travel/contentassets/8012a18b4b784e889f3d2c700448b454/museum-situs-kepurbakalaan-banten-lama.jpg',
            'Masjid Agung Banten' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Masjid_agung_banten_lama.jpg',
            'Rabeg Khas Banten' => 'https://foodnesia.net/wp-content/uploads/2020/01/rabeg-khas-banten.jpg',
            'Pantai Anyer' => 'https://cilegonhills.id/wp-content/uploads/2020/12/Pantai-Anyer-1140px-x-740px.jpg',
            'Telur Asin Brebes' => 'https://awsimages.detik.net.id/api/wm/2022/12/14/telur-asin_169.jpeg?wid=60&w=1200&v=1&t=jpeg',
            'Sentra Bawang Merah Brebes' => 'https://img.antarafoto.com/cache/1200x772/2020/12/19/harga-bawang-merah-di-brebes-turun-s718-dom.jpg',
            'Pantai Widuri Pemalang' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Senja_di_Pantai_Widuri.jpg/1280px-Senja_di_Pantai_Widuri.jpg',
            'Pantai Ngebum Kendal' => 'https://img.antarafoto.com/cache/1200x746/2017/08/01/wisata-pantai-ngebum-kendal-fdv9-dom.webp',
            'Masjid Agung Demak' => 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Masjid_demak.jpg',
            'Makam Sunan Kalijaga' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/cf/8b/f6/makam-sunan-kalijaga.jpg?w=1200&h=-1&s=1',
            'Bandeng Presto Demak' => 'https://awsimages.detik.net.id/community/media/visual/2020/11/11/bandeng-presto-2.jpeg?w=2848',
            'Bledug Kuwu' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Bledug_Kuwu_2.jpg/250px-Bledug_Kuwu_2.jpg',
            'Hutan Jati Blora' => 'https://awsimages.detik.net.id/community/media/visual/2024/03/31/jati-denok-di-wilayah-hutan-desa-jatisari-kecamatan-banjarejo-kabupaten-blora-jumat-2932024-3_43.jpeg?w=1200',
            'Sate Ayam Blora' => 'https://upload.wikimedia.org/wikipedia/commons/9/93/Sate_Blora.jpg',
            'Candi Cetho' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/1d/9b/1f/candi-cetho.jpg?w=1200&h=-1&s=1',
            'Kebun Teh Kemuning' => 'https://awsimages.detik.net.id/community/media/visual/2023/08/07/kebun-teh-kemuning-1_169.jpeg?w=1200',
            'Museum Purbakala Sangiran (UNESCO)' => 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Museum_Purbakala_Sangiran_1.JPG',
            'Waduk Gajah Mungkur' => 'https://upload.wikimedia.org/wikipedia/commons/5/59/Gajah_Mungkur_dam.jpg',
            'Pantai Karangbolong Kebumen' => 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Pantai_Karang_Bolong_di_Kabupaten_Kebumen_Indonesia.jpg',
            'Lanting Kebumen' => 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Lanting_makanan_khas_kebumen.webp',
            'Pantai Ketawang Purworejo' => 'https://www.gotravelly.com/blog/wp-content/uploads/2023/10/pantai-ketawang.jpg',
            'Kue Clorot Purworejo' => 'https://imgcdn.espos.id/@espos/images/2023/03/Kue-Clorot-Khas-Purworejo.jpg',
            'Benteng Pendem Cilacap' => 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Entrance%2C_Benteng_Pendem%2C_Cilacap_2015-03-21.jpg',
            'Pantai Teluk Penyu' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Dock%2C_Teluk_Penyu_Beach%2C_Cilacap_2015-03-21.jpg/1280px-Dock%2C_Teluk_Penyu_Beach%2C_Cilacap_2015-03-21.jpg',
            'Pantai Glagah Kulon Progo' => 'https://upload.wikimedia.org/wikipedia/commons/d/db/Glagah_Beach_Kulon_Progo.jpg',
            'Puncak Saka Kulon Progo' => 'https://awsimages.detik.net.id/community/media/visual/2021/12/17/puncak-saka-kulon-progo-yogyakarta-3_169.jpeg?w=1200',
            'Makam Sunan Giri' => 'https://www.nativeindonesia.com/foto/2023/07/makam-sunan-giri-gresik.jpg',
            'Otak-Otak Bandeng Gresik' => 'https://i0.wp.com/elrajab.com/wp-content/uploads/2018/08/makanan-khas-gresik-otak-otak-bandeng.jpg?w=667&ssl=1',
            'Candi Pari Sidoarjo' => 'https://upload.wikimedia.org/wikipedia/commons/1/17/Candi_Pari_1.jpg',
            'Onde-Onde Mojokerto' => 'https://assets-a1.kompasiana.com/items/album/2025/01/22/onde-onde-6791082fed64156701588f02.jpg',
            'Agrowisata Wonosalam Jombang' => 'https://travelspromo.com/wp-content/uploads/2023/07/duran-duren-wonosalam-jombang-1200x900.jpg',
            'Kayangan Api (Api Abadi Bojonegoro)' => 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Kayangan_Api_Bojonegoro1.jpg',
            'Wisata Bahari Lamongan (WBL)' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/fc/8f/09/wisata-bahari-lamongan.jpg?w=800&h=-1&s=1',
            'Soto Lamongan Cak Mun' => 'https://7terbaik.com/wp-content/uploads/2018/10/Soto-Lamongan-Cak-Har-1024x683.jpg',
            'Museum Trinil Ngawi' => 'https://upload.wikimedia.org/wikipedia/commons/4/43/Museum_trinil.jpg',
            'Tahu Ngawi' => 'https://bisnisukm.com/uploads/2021/02/usaha-tahu-tepo-kuliner-khas-ngawi-yang-gampang-bikinnya-720x414.png',
            'Kerajinan Kulit Magetan' => 'https://www.sepatukulitmagetan.net/upload/post/tepo-tahu-khas-magetan.jpg',
            'Sentra Kerajinan Kulit Magetan' => 'https://cdn.antaranews.com/cache/1200x800/2026/03/19/sandal-kulit-magetan.jpeg',
            'Taman Safari Prigen' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Taman_Safari_Prigen%2C_Jawa_Timur.jpg/1280px-Taman_Safari_Prigen%2C_Jawa_Timur.jpg',
            'Air Terjun Kakek Bodo' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/fe/7a/1a/kakek-bodo-legendary.jpg?w=1200&h=1200&s=1',
            'Bandeng Asap Pasuruan' => 'https://awsimages.detik.net.id/content/2011/07/04/482/bandengasapcvr.jpg?w=650',
            'Pantai Bentar Probolinggo' => 'https://upload.wikimedia.org/wikipedia/commons/3/32/Pemandangan_wisata_Pantai_Bentar_Probolinggo.png',
            'Coban Sewu (Tumpak Sewu)' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Air_Terjun_Tumpak_Sewu.jpg/960px-Air_Terjun_Tumpak_Sewu.jpg',
            'Pisang Agung Lumajang' => 'https://foodnesia.net/wp-content/uploads/2019/11/pisang-agung-lumajang.jpg',
            'Pantai Popoh Tulungagung' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/97/cf/1f/pantai-popoh-tulungagung.jpg?w=700&h=400&s=1',
            'Ayam Lodho Tulungagung' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ayam_Lodho_Khas_Tulungagung.jpg/960px-Ayam_Lodho_Khas_Tulungagung.jpg',
            'Tebing Citatah' => 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Citatah_Cliff_Sumit.jpg',
            'Keramik Plered Bandung Barat' => 'https://lovebandung.com/wp-content/uploads/2023/07/1688779378075.jpg',
            'Oncom Cimahi' => 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Oncom.jpg',
            'Galendo (Ampas Minyak Kelapa) Ciamis' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Galendo.jpg/1280px-Galendo.jpg',
            'Kawah Kamojang' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/ac/36/b0/kamojang-crater.jpg?w=1200&h=1200&s=1',
            'Kawasan SCBD & Sudirman' => 'https://upload.wikimedia.org/wikipedia/commons/8/85/SCBD%2C_Jakarta.jpg',
            'Pasar Intermoda BSD' => 'https://cms.sinarmasland.com/uploads/Intermoda_BSD_City_45ed63930c.jpg',
            'Kampung Adat Baduy' => 'https://upload.wikimedia.org/wikipedia/commons/5/59/Rumah_Tradisional_Warga_Baduy_Luar_1.jpg',
            'Batik Tulis Batang' => 'https://hypeabis.id/assets/content/batik_202502260537271740523047.jpg',
            'Klengkeng Kopyor Kendal' => 'https://cdn.antarafoto.com/cache/1200x798/2008/11/02/klengkeng-10kn-dom.jpg',
            'Api Abadi Mrapen' => 'https://visitjawatengah.jatengprov.go.id/assets/images/mrapen-eternal-fire.jpg',
            'Susu Sapi Segar Boyolali' => 'https://imgcdn.espos.id/@espos/images/2022/09/rsz_16_ikon_boyolali.jpg?width=500&height=300&quality=60',
            'Goa Gong Wonogiri' => 'https://marleneonthemove.com/wp-content/uploads/2017/09/goagong-6-1-scaled.jpg.webp',
            'Benteng Van der Wijck' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Fort_van_der_Wijck_-_Entrance.JPG/1280px-Fort_van_der_Wijck_-_Entrance.JPG',
            'Lokawisata Baturraden' => 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Baturraden_overview_from_ridge%2C_Purwokerto%2C_2015-03-23.jpg',
            'Mendoan Banyumas' => 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Mendoan.jpg',
            'Pesantren Tebuireng & Makam Gus Dur' => 'https://tebuireng.online/wp-content/uploads/2020/08/tebuireng-jombang-2.jpg',
            'Kerajinan Kayu Jati Bojonegoro' => 'https://forumradiobojonegoro.com/wp-content/uploads/2016/12/20161231_133537.jpg',
            'Air Terjun Sedudo' => 'https://www.indonesia-tourism.com/east-java/tourism/nganjuk/images/sedudo.jpg',
            'Benteng Pendem Ngawi' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Benteng_van_den_bosch.jpg/250px-Benteng_van_den_bosch.jpg',
            'Industri Marmer Tulungagung' => 'https://www.indonesia-tourism.com/east-java/tourism/tulungagung/images/marble-1.jpg',
            'Pantai Tanjung Pakis' => 'https://asset.kompas.com/crops/0SktC9UOtaExDHwjVDzrvyVsFrk=/0x0:999x666/1200x1200/data/photo/2020/06/02/5ed637ccaed86.jpg',
            'Waduk Jatiluhur' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Another_View_of_Jati_Luhur.jpg/1280px-Another_View_of_Jati_Luhur.jpg',
            'Sate Maranggi H. Yetty' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/2a/c8/77/img-20190908-111224-largejpg.jpg?w=900&h=500&s=1',
            'Kue Simping Purwakarta' => 'https://www.djkn.kemenkeu.go.id/files/images/2022/06/vlcsnap-2022-06-29-08h41m20s183.png',
            'Dodol Garut Picnic' => 'https://cf.shopee.co.id/file/ee6b3262a66738e94ffa6c4621eebc41',
            'Pemandian Air Panas Cipanas Garut' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/9b/5d/c0/wisata-air-dan-resort.jpg?w=1200&h=-1&s=1',
            'Gelora Bung Karno (GBK)' => 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Asian_Games_2018_GBK_Stadium_10.jpg',
            'Menteng Heritage Food Court' => null,
            'Nasi Uduk Tanah Abang Pak Wahid' => null,
            'Mie Ayam Mat Lengket Jatinegara' => null,
            'Krakatau Steel Industrial Area' => null,
            'Kain Tenun Baduy' => 'https://asset.kompas.com/crops/WdrhcO-sj8MXd2VWc2igZ5G0QBg=/0x0:1776x1184/750x500/data/photo/2019/10/23/5daffd05be159.jpg',
            'Pantai Sigandu Batang' => 'https://visitjawatengah.jatengprov.go.id/assets/images/35efa156-a62e-4c4c-b1ed-4b862f490e761.jpg',
            'Grombyang Pemalang' => 'https://visitjawatengah.jatengprov.go.id/assets/images/8a3e6511-50fc-4fb4-8ed4-33bcba535218.jpg',
            'Kawasan Wisata Selo (Gunung Merapi-Merbabu)' => 'https://asset.kompas.com/crops/HukxYzetvo71f5SEDCQAie8bE0o=/0x0:1200x800/750x500/data/photo/2020/08/21/5f3fdc5a6c81d.jpg',
            'Candi Sukuh' => 'https://visitjawatengah.jatengprov.go.id/assets/images/990f915f-73d9-4e8e-a2d3-3eda0307de7e.jpg',
            'Nasi Jagung Bu Slamet Sragen' => null,
            'Sentra Batik Sukoharjo' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/46/a3/f4/photogrid-1556119620140.jpg?w=900&h=500&s=1',
            'Timlo Solo Sastro' => 'https://static.republika.co.id/uploads/images/inpicture_slide/012990200-1703572218-830-556.jpg',
            'Bakso dan Mie Wonogiri' => null,
            'Getuk Goreng Sokaraja' => null,
            'Lanting Cilacap' => null,
            'Gebleg Kulon Progo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/27._Gebl%C3%A8k_1.jpg/1280px-27._Gebl%C3%A8k_1.jpg',
            'Bukit Kapur Sekapuk Gresik' => 'https://asset.kompas.com/crops/qMYwr4qVDsGbgfBE-Atcp3OqnIE=/0x0:0x0/1200x1200/data/photo/2020/07/29/5f2184312791a.jpg',
            'Sentra Tas & Koper Tanggulangin' => 'https://asset.kompas.com/crops/d_DIsLl2CxVloq7eJ5In5Zjjcsk=/0x0:0x0/1200x675/data/photo/2026/03/25/69c311ea61fa3.jpg',
            'Petis Udang Sidoarjo' => 'https://img-global.cpcdn.com/recipes/6233dbf18183b9c8/1200x630cq80/photo.jpg',
            'Situs Trowulan (Ibu Kota Majapahit)' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Eksotika_Candi_Bajang_Ratu.jpg/1280px-Eksotika_Candi_Bajang_Ratu.jpg',
            'Museum Majapahit Trowulan' => 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Airlangga.jpg',
            'Kupang Lamongan' => 'https://cdn0-production-images-kly.akamaized.net/_QqaNbAJmt8_QFdF5LFJgw0UxFw=/500x281/kly-media-production/medias/3911576/original/001955400_1642842581-shutterstock_2058946475.jpg',
            'Bawang Merah Nganjuk' => 'https://cdn.antaranews.com/cache/1200x800/2019/08/19/2.jpg',
            'Telaga Sarangan' => null,
            'Lontong Tahu Magetan' => null,
            'Gunung Bromo (via Probolinggo)' => 'https://asset.kompas.com/crops/PmlMqU_I4pi_yvGUtmQ1PT5Z9IM=/0x0:1800x1200/1200x800/data/photo/2021/05/10/6099375e04acb.jpg',
            'Mangga Probolinggo (Manalagi & Arumanis)' => 'https://asset.kompas.com/crops/IFKb2xEzIXZDAmWYG9VjLw0IFFI=/0x0:1000x667/1200x800/data/photo/2022/06/18/62ad543a532ab.jpg',
        ];

        $updated = 0;
        foreach ($fotos as $nama => $foto) {
            $rows = Destinasi::where('nama', $nama)->update(['foto' => $foto]);
            $updated += $rows;
        }
        $this->command->info("Updated foto for {$updated} destinasi.");
    }
}
