<?php

namespace Database\Seeders;

use App\Models\Kota;
use App\Models\Stasiun;
use Illuminate\Database\Seeder;

class StasiunSeeder extends Seeder
{
    public function run(): void
    {
        // Format: [kode_stasiun, nama, nama_kota]
        $daftarStasiun = [
            ['AC', 'Ancol', 'Jakarta Utara'],
            ['AK', 'Angke', 'Jakarta Barat'],
            ['BSH', 'Bandara Soekarno Hatta', 'Tangerang'],
            ['BPR', 'Batuceper', 'Tangerang'],
            ['BTT', 'Batutulis', 'Bogor'],
            ['BUA', 'Bauran', 'Jakarta Timur'],
            ['BKS', 'Bekasi', 'Bekasi'],
            ['BKT', 'Bekasi Timur', 'Bekasi'],
            ['BOO', 'Bogor', 'Bogor'],
            ['BJD', 'Bojonggede', 'Bogor'],
            ['BOI', 'Bojongindah', 'Jakarta Barat'],
            ['CUK', 'Cakung', 'Jakarta Timur'],
            ['CT', 'Catang', 'Serang'],
            ['CW', 'Cawang', 'Jakarta Selatan'],
            ['CBD', 'Cibadak', 'Sukabumi'],
            ['CBN', 'Cibinong', 'Bogor'],
            ['CIT', 'Cibitung', 'Bekasi'],
            ['CC', 'Cicayur', 'Tangerang'],
            ['CCR', 'Cicurug', 'Sukabumi'],
            ['CGD', 'Cigading', 'Cilegon'],
            ['CGB', 'Cigombong', 'Bogor'],
            ['CKP', 'Cikampek', 'Karawang'],
            ['CKR', 'Cikarang', 'Bekasi'],
            ['CKL', 'Cikeusal', 'Serang'],
            ['CKI', 'Cikini', 'Jakarta Pusat'],
            ['CKY', 'Cikoya', 'Tangerang'],
            ['CLT', 'Cilebut', 'Bogor'],
            ['CLG', 'Cilegon', 'Cilegon'],
            ['CJT', 'Cilejit', 'Tangerang'],
            ['CS', 'Ciomas', 'Bogor'],
            ['CPN', 'Cipinang', 'Jakarta Timur'],
            ['CSA', 'Cisaat', 'Sukabumi'],
            ['CSK', 'Cisauk', 'Tangerang'],
            ['CTA', 'Citayam', 'Depok'],
            ['CTR', 'Citeras', 'Lebak'],
            ['DAR', 'Daru', 'Tangerang'],
            ['DP', 'Depok', 'Depok'],
            ['DPB', 'Depokbaru', 'Depok'],
            ['DRN', 'Durenkalibata', 'Jakarta Selatan'],
            ['DU', 'Duri', 'Jakarta Barat'],
            ['DWN', 'Dauwan', 'Karawang'],
            ['GDD', 'Gondangdia', 'Jakarta Pusat'],
            ['GGL', 'Grogol', 'Jakarta Barat'],
            ['GMR', 'Gambir', 'Jakarta Pusat'],
            ['GPI', 'Gunungputri', 'Bogor'],
            ['GST', 'Gangsentiong', 'Jakarta Pusat'],
            ['JAKG', 'Jakarta Gudang', 'Jakarta Utara'],
            ['JAKK', 'Jakarta Kota', 'Jakarta Utara'],
            ['JAY', 'Jayakarta', 'Jakarta Pusat'],
            ['JBU', 'Jambubaru', 'Serang'],
            ['JICT', 'Jakarta International Ct', 'Jakarta Utara'],
            ['JMU', 'Jurangmangu', 'Tangerang Selatan'],
            ['JNG', 'Jatinegara', 'Jakarta Timur'],
            ['JUA', 'Juanda', 'Jakarta Pusat'],
            ['KAT', 'Karet', 'Jakarta Pusat'],
            ['KBY', 'Kebayoran', 'Jakarta Selatan'],
            ['KDH', 'Kedunggedeh', 'Bekasi'],
            ['KDS', 'Kalideres', 'Jakarta Barat'],
            ['KE', 'Karangtengah', 'Sukabumi'],
            ['KEN', 'Krenceng', 'Cilegon'],
            ['KLD', 'Klender', 'Jakarta Timur'],
            ['KLDB', 'Klenderbaru', 'Jakarta Timur'],
            ['KLI', 'Klari', 'Karawang'],
            ['KMO', 'Kemayoran', 'Jakarta Pusat'],
            ['KMT', 'Kramat', 'Jakarta Pusat'],
            ['KOS', 'Kosambi', 'Karawang'],
            ['KPB', 'Kampung Bandan', 'Jakarta Utara'],
            ['KRA', 'Karangantu', 'Serang'],
            ['KRI', 'Kranji', 'Bekasi'],
            ['KW', 'Karawang', 'Karawang'],
            ['LMB', 'Lemahabang', 'Bekasi'],
            ['LNA', 'Lentengagung', 'Jakarta Selatan'],
            ['MER', 'Merak', 'Cilegon'],
            ['MGB', 'Manggabesar', 'Jakarta Pusat'],
            ['MJA', 'Maja', 'Lebak'],
            ['MPG', 'Mampang', 'Jakarta Pusat'],
            ['MRI', 'Manggarai', 'Jakarta Selatan'],
            ['MSG', 'Maseng', 'Bogor'],
            ['NMO', 'Nambo', 'Bogor'],
            ['PDC', 'Pondokcina', 'Depok'],
            ['PDR', 'Pondokranji', 'Tangerang Selatan'],
            ['PDRG', 'Pondokrajeg', 'Bogor'],
            ['PI', 'Poris', 'Tangerang'],
            ['PLM', 'Palmerah', 'Jakarta Pusat'],
            ['POK', 'Pondokjati', 'Jakarta Timur'],
            ['PON', 'Pondokkleungsir', 'Sukabumi'],
            ['POO', 'Pasoso', 'Jakarta Utara'],
            ['PRK', 'Parungkuda', 'Sukabumi'],
            ['PRP', 'Parungpanjang', 'Bogor'],
            ['PSE', 'Pasar Senen', 'Jakarta Pusat'],
            ['PSG', 'Pesing', 'Jakarta Barat'],
            ['PSM', 'Pasarminggu', 'Jakarta Selatan'],
            ['PSMB', 'Pasarminggubaru', 'Jakarta Selatan'],
            ['RJW', 'Rajawali', 'Jakarta Pusat'],
            ['RK', 'Rangkasbitung', 'Lebak'],
            ['RU', 'Rawabuntu', 'Tangerang Selatan'],
            ['RW', 'Rawabuaya', 'Jakarta Barat'],
            ['RWB', 'Rawabebek', 'Bekasi'],
            ['SAO', 'Sungailagoa', 'Jakarta Utara'],
            ['SDM', 'Sudimara', 'Tangerang Selatan'],
            ['SG', 'Serang', 'Serang'],
            ['SI', 'Sukabumi', 'Sukabumi'],
            ['SRP', 'Serpong', 'Tangerang Selatan'],
            ['SUD', 'Sudirman/Dukuhatas', 'Jakarta Pusat'],
            ['SW', 'Sawahbesar', 'Jakarta Pusat'],
            ['TAJ', 'Tonjongbaru', 'Serang'],
            ['TAK', 'Tamankota', 'Jakarta Barat'],
            ['TB', 'Tambun', 'Bekasi'],
            ['TEB', 'Tebet', 'Jakarta Selatan'],
            ['TGS', 'Tigaraksa', 'Tangerang'],
            ['THB', 'Tanahabang', 'Jakarta Pusat'],
            ['THL', 'Tanahtinggi', 'Tangerang'],
            ['TJ', 'Tenjo', 'Bogor'],
            ['TNG', 'Tangerang', 'Tangerang'],
            ['TNT', 'Tajungbarat', 'Jakarta Selatan'],
            ['TPK', 'Tanjung Priuk', 'Jakarta Utara'],
            ['UI', 'Universitasindonesia', 'Depok'],
            ['UP', 'Universitaspancasila', 'Jakarta Selatan'],
            ['WLT', 'Walantaka', 'Serang'],
            ['AND', 'Andir', 'Bandung'],
            ['AW', 'Awipari', 'Tasikmalaya'],
            ['BD', 'Bandung', 'Bandung'],
            ['BJR', 'Banjar', 'Banjar'],
            ['BJG', 'Bojong', 'Ciamis'],
            ['BMW', 'Bumiwaluya', 'Garut'],
            ['CI', 'Ciamis', 'Ciamis'],
            ['CJ', 'Cianjur', 'Cianjur'],
            ['CAW', 'Ciawi', 'Tasikmalaya'],
            ['CB', 'Cibatu', 'Garut'],
            ['CBB', 'Cibeber', 'Cianjur'],
            ['CBR', 'Cibungur', 'Purwakarta'],
            ['CCL', 'Cicalengka', 'Bandung'],
            ['CA', 'Ciganea', 'Purwakarta'],
            ['CD', 'Cikadongdong', 'Bandung Barat'],
            ['CTH', 'Cikudapateuh', 'Bandung'],
            ['CLK', 'Cilaku', 'Cianjur'],
            ['CLE', 'Cilame', 'Bandung Barat'],
            ['CMI', 'Cimahi', 'Cimahi'],
            ['CMK', 'Cimekar', 'Bandung'],
            ['CMD', 'Cimindi', 'Bandung'],
            ['CPT', 'Cipatat', 'Bandung Barat'],
            ['CPD', 'Cipeundeuy', 'Garut'],
            ['CPY', 'Cipeuyeum', 'Cianjur'],
            ['CAA', 'Cirahayu', 'Tasikmalaya'],
            ['CRJ', 'Ciranjang', 'Cianjur'],
            ['CRG', 'Cireungas', 'Sukabumi'],
            ['CIR', 'Ciroyom', 'Bandung'],
            ['CG', 'Cisomang', 'Purwakarta'],
            ['GDB', 'Gedebage', 'Bandung'],
            ['GDS', 'Gandasoli', 'Sukabumi'],
            ['GK', 'Godabangkong', 'Bandung Barat'],
            ['HRP', 'Haurpugur', 'Bandung'],
            ['IH', 'Indihiang', 'Tasikmalaya'],
            ['KAC', 'Kiaracondong', 'Bandung'],
            ['KNP', 'Karangpucung', 'Banjar'],
            ['KRAI', 'Karangsari', 'Garut'],
            ['LBJ', 'Lebakjero', 'Bandung'],
            ['LL', 'Leles', 'Garut'],
            ['LO', 'Leuwigoong', 'Garut'],
            ['LP', 'Lampegan', 'Cianjur'],
            ['MLB', 'Maleber', 'Cianjur'],
            ['MNJ', 'Manojaya', 'Tasikmalaya'],
            ['MSI', 'Maswati', 'Bandung Barat'],
            ['NG', 'Nagreg', 'Bandung'],
            ['PDL', 'Padalarang', 'Bandung Barat'],
            ['PLD', 'Plered', 'Purwakarta'],
            ['PWK', 'Purwakarta', 'Purwakarta'],
            ['RCK', 'Rancaekek', 'Bandung'],
            ['RH', 'Rendeh', 'Bandung Barat'],
            ['RI', 'Ranji', 'Sukabumi'],
            ['RJP', 'Rajapolah', 'Tasikmalaya'],
            ['RM', 'Rajamandala', 'Bandung Barat'],
            ['SAD', 'Sadang', 'Purwakarta'],
            ['SKT', 'Sasaksaat', 'Bandung Barat'],
            ['SLJ', 'Selajambe', 'Cianjur'],
            ['SSI', 'Sindangresmi', 'Cianjur'],
            ['SUT', 'Sukatani', 'Purwakarta'],
            ['TAU', 'Tagogapu', 'Bandung Barat'],
            ['TPR', 'Tipar', 'Cianjur'],
            ['TSM', 'Tasikmalaya', 'Tasikmalaya'],
            ['WB', 'Warungbandrek', 'Garut'],
            ['AWN', 'Arjawinangun', 'Cirebon'],
            ['BBK', 'Babakan', 'Cirebon'],
            ['BDW', 'Bangodua', 'Cirebon'],
            ['BB', 'Brebes', 'Brebes'],
            ['BKA', 'Bulakamba', 'Brebes'],
            ['CNK', 'Cangkring', 'Cirebon'],
            ['CKM', 'Cikaum', 'Subang'],
            ['CLD', 'Cileduk', 'Cirebon'],
            ['CLH', 'Cilegeh', 'Indramayu'],
            ['CRA', 'Cipunegara', 'Subang'],
            ['CN', 'Cirebon', 'Cirebon'],
            ['CNP', 'Cirebonprujakan', 'Cirebon'],
            ['HGL', 'Haurgeulis', 'Indramayu'],
            ['JTB', 'Jatibarang', 'Indramayu'],
            ['KAB', 'Kadokagabus', 'Indramayu'],
            ['KGB', 'Ketanggunganbarat', 'Brebes'],
            ['KGG', 'Ketanggungan', 'Brebes'],
            ['KLW', 'Kaliwedi', 'Cirebon'],
            ['KRW', 'Karangsuwung', 'Cirebon'],
            ['KTM', 'Kertasemaya', 'Indramayu'],
            ['LOS', 'Losari', 'Cirebon'],
            ['LRA', 'Larangan', 'Brebes'],
            ['LWG', 'Luwung', 'Cirebon'],
            ['PAB', 'Pabuaran', 'Subang'],
            ['PAS', 'Pasirbungur', 'Subang'],
            ['PGB', 'Pegadenbaru', 'Subang'],
            ['PRI', 'Pringkasp', 'Subang'],
            ['SDU', 'Sindanglaut', 'Cirebon'],
            ['SGG', 'Songgom', 'Brebes'],
            ['TGN', 'Tanjung', 'Brebes'],
            ['TIS', 'Terisi', 'Indramayu'],
            ['TJS', 'Tanjungrasa', 'Subang'],
            ['TLS', 'Telagasari', 'Indramayu'],
            ['WDW', 'Waruduwur', 'Cirebon'],
            ['ATA', 'Alastuwa', 'Semarang'],
            ['BTG', 'Batang', 'Batang'],
            ['BBG', 'Brumbung', 'Demak'],
            ['CU', 'Cepu', 'Blora'],
            ['CO', 'Comal', 'Pemalang'],
            ['DPL', 'Doplang', 'Grobogan'],
            ['GBN', 'Gambringan', 'Grobogan'],
            ['GD', 'Gundih', 'Grobogan'],
            ['GN', 'Gedangan', 'Grobogan'],
            ['GUB', 'Gubug', 'Grobogan'],
            ['JBN', 'Jambon', 'Grobogan'],
            ['JBN1', 'Jambean', 'Boyolali'],
            ['JRK', 'Jarakah', 'Semarang'],
            ['JTS', 'Jetis', 'Grobogan'],
            ['KBD', 'Kalibodri', 'Kendal'],
            ['KEJ', 'Kedungjati', 'Grobogan'],
            ['KGT', 'Karangjati', 'Grobogan'],
            ['KIT', 'Kalitidu', 'Bojonegoro'],
            ['KLN', 'Kaliwungu', 'Kendal'],
            ['KNN', 'Kradean', 'Grobogan'],
            ['KNS', 'Krengseng', 'Batang'],
            ['KPA', 'Kapuan', 'Blora'],
            ['KRP', 'Kuripan', 'Batang'],
            ['KSO', 'Karangsono', 'Grobogan'],
            ['LR', 'Larang', 'Tegal'],
            ['MKG', 'Mangkang', 'Semarang'],
            ['NBO', 'Ngrombo', 'Grobogan'],
            ['PDS', 'Padas', 'Grobogan'],
            ['PK', 'Pekalongan', 'Pekalongan'],
            ['PLB', 'Plabuhan', 'Batang'],
            ['PML', 'Pemalang', 'Pemalang'],
            ['PNL', 'Panunggalan', 'Grobogan'],
            ['PTA', 'Petarukan', 'Pemalang'],
            ['RBG', 'Randublatung', 'Blora'],
            ['SD', 'Surodadi', 'Tegal'],
            ['SDI', 'Sedadi', 'Grobogan'],
            ['SL', 'Sulur', 'Grobogan'],
            ['SMC', 'Semarang Poncol', 'Semarang'],
            ['SMC1', 'Semarangponcol', 'Semarang'],
            ['SMT', 'Semarang Tawang', 'Semarang'],
            ['SRI', 'Sragi', 'Pekalongan'],
            ['TBO', 'Tobo', 'Bojonegoro'],
            ['TG', 'Tegal', 'Tegal'],
            ['TGG', 'Tanggung', 'Grobogan'],
            ['TGW', 'Tegowanu', 'Grobogan'],
            ['TRH', 'Toroh', 'Grobogan'],
            ['TW', 'Telawa', 'Boyolali'],
            ['UJN', 'Ujungnegoro', 'Batang'],
            ['WDU', 'Wadu', 'Blora'],
            ['WLR', 'Weleri', 'Kendal'],
            ['BMA', 'Bumiayu', 'Brebes'],
            ['BTH', 'Butuh', 'Purworejo'],
            ['CKW', 'Cikawung', 'Ciamis'],
            ['CP', 'Cilacap', 'Cilacap'],
            ['CPI', 'Cipari', 'Cilacap'],
            ['GB', 'Gombong', 'Kebumen'],
            ['GDM', 'Gandrungmangun', 'Cilacap'],
            ['GM', 'Gumilir', 'Cilacap'],
            ['IJ', 'Ijo', 'Kebumen'],
            ['JRL', 'Jeruklegi', 'Cilacap'],
            ['KA', 'Karanganyar', 'Kebumen'],
            ['KBS', 'Kebasen', 'Banyumas'],
            ['KGD', 'Karanggandul', 'Banyumas'],
            ['KH', 'Kesugihan', 'Cilacap'],
            ['KJ', 'Kemranjen', 'Banyumas'],
            ['KKD', 'Karangkadri', 'Cilacap'],
            ['KM', 'Kebumen', 'Kebumen'],
            ['KRL', 'Karangtalun', 'Cilacap'],
            ['KRR', 'Karangsari', 'Banyumas'],
            ['KRT', 'Kretek', 'Brebes'],
            ['KTA', 'Kutoarjo', 'Purworejo'],
            ['KWG', 'Kawunganten', 'Cilacap'],
            ['KWN', 'Kutowinangun', 'Kebumen'],
            ['KYA', 'Kroya', 'Cilacap'],
            ['LBG', 'Lebeng', 'Cilacap'],
            ['LG', 'Linggapura', 'Brebes'],
            ['LGK', 'Legok', 'Banyumas'],
            ['LN', 'Langen', 'Banjar'],
            ['MA', 'Maos', 'Cilacap'],
            ['MLW', 'Meluwung', 'Cilacap'],
            ['NTG', 'Notog', 'Banyumas'],
            ['PAT', 'Patuguran', 'Brebes'],
            ['PKW', 'Pasarkliwon', 'Cilacap'],
            ['PPK', 'Prupuk', 'Tegal'],
            ['PRB', 'Prembun', 'Kebumen'],
            ['PWR', 'Purworejo', 'Purworejo'],
            ['PWT', 'Purwokerto', 'Banyumas'],
            ['RDN', 'Randegan', 'Cilacap'],
            ['SDR', 'Sidareja', 'Cilacap'],
            ['SIL', 'Sitinggil', 'Cilacap'],
            ['SKP', 'Sikampuh', 'Cilacap'],
            ['SOA', 'Soka', 'Kebumen'],
            ['SPH', 'Sumpiuh', 'Banyumas'],
            ['SRW', 'Sruweng', 'Kebumen'],
            ['TBK', 'Tambak', 'Banyumas'],
            ['WNS', 'Wonosari', 'Kebumen'],
            ['BBN', 'Brambanan', 'Klaten'],
            ['CE', 'Ceper', 'Klaten'],
            ['DL', 'Dlanggu', 'Klaten'],
            ['GPK', 'Goprak', 'Grobogan'],
            ['GW', 'Gawok', 'Sukoharjo'],
            ['JN', 'Jenar', 'Purworejo'],
            ['KDB', 'Kedungbanteng', 'Sragen'],
            ['KLS', 'Kalasan', 'Sleman'],
            ['KMR', 'Kemiri', 'Karanganyar'],
            ['KO', 'Kalioso', 'Karanganyar'],
            ['KRO', 'Kebonromo', 'Sragen'],
            ['KT', 'Klaten', 'Klaten'],
            ['LPN', 'Lempuyangan', 'Yogyakarta'],
            ['MGW', 'Maguwo', 'Sleman'],
            ['MSR', 'Masaran', 'Sragen'],
            ['PL', 'Palur', 'Karanganyar'],
            ['PNT', 'Pasarnguter', 'Sukoharjo'],
            ['PTN', 'Patukan', 'Sleman'],
            ['PWS', 'Purwosari', 'Solo'],
            ['RWL', 'Rewulu', 'Bantul'],
            ['SK', 'Solojebres', 'Solo'],
            ['SKH', 'Sukoharjo', 'Sukoharjo'],
            ['SLM', 'Salem', 'Sragen'],
            ['SLO', 'Solo Balapan', 'Solo'],
            ['SR', 'Sragen', 'Sragen'],
            ['STA', 'Slo Kota', 'Solo'],
            ['STL', 'Sentolo', 'Kulon Progo'],
            ['SUM', 'Sumberlawang', 'Sragen'],
            ['SWT', 'Srowot', 'Klaten'],
            ['WJ', 'Wojo', 'Purworejo'],
            ['WNG', 'Wonogiri', 'Wonogiri'],
            ['WT', 'Wates', 'Kulon Progo'],
            ['YK', 'Yogyakarta', 'Yogyakarta'],
            ['BBD', 'Babadan', 'Madiun'],
            ['BGR', 'Bagor', 'Nganjuk'],
            ['BAT', 'Barat', 'Magetan'],
            ['BRN', 'Baron', 'Madiun'],
            ['BL', 'Blitar', 'Blitar'],
            ['CRB', 'Caruban', 'Madiun'],
            ['CRM', 'Curahmalang', 'Jombang'],
            ['GG', 'Geneng', 'Ngawi'],
            ['GRM', 'Garum', 'Madiun'],
            ['JG', 'Jombang', 'Jombang'],
            ['KD', 'Kediri', 'Kediri'],
            ['KG', 'Kedunggalar', 'Ngawi'],
            ['KRS', 'Kras', 'Kediri'],
            ['KTS', 'Kertosono', 'Nganjuk'],
            ['MAG', 'Magetan', 'Madiun'],
            ['MGN', 'Minggiran', 'Kediri'],
            ['MN', 'Madiun', 'Madiun'],
            ['NDL', 'Ngadiluwih', 'Kediri'],
            ['NGW', 'Ngawi', 'Ngawi'],
            ['NJ', 'Nganjuk', 'Nganjuk'],
            ['NJG', 'Ngujang', 'Tulungagung'],
            ['NT', 'Ngunut', 'Tulungagung'],
            ['PA', 'Paron', 'Ngawi'],
            ['PPR', 'Papar', 'Kediri'],
            ['PTR', 'Peterongan', 'Jombang'],
            ['PWA', 'Purwoasri', 'Kediri'],
            ['RJ', 'Rejotangan', 'Tulungagung'],
            ['SBL', 'Sumbrgempol', 'Tulungagung'],
            ['SBO', 'Sumobito', 'Jombang'],
            ['SKM', 'Sukomoro', 'Nganjuk'],
            ['SMB', 'Sembung', 'Jombang'],
            ['SRD', 'Saradan', 'Madiun'],
            ['SS', 'Susuhan', 'Kediri'],
            ['TA', 'Tulungagung', 'Tulungagung'],
            ['TAL', 'Talun', 'Madiun'],
            ['WK', 'Walikukun', 'Ngawi'],
            ['WLG', 'Wilangan', 'Nganjuk'],
            ['BBT', 'Babat', 'Lamongan'],
            ['BG', 'Bangil', 'Pasuruan'],
            ['BAL', 'Bangsal', 'Mojokerto'],
            ['BJN', 'Banjarkemantren', 'Sidoarjo'],
            ['BNW', 'Benowo', 'Surabaya'],
            ['BET', 'Benteng', 'Surabaya'],
            ['BMG', 'Blimbing', 'Malang'],
            ['BH', 'Boharan', 'Sidoarjo'],
            ['BJ', 'Bojonegoro', 'Bojonegoro'],
            ['BWO', 'Bowerno', 'Bojonegoro'],
            ['BDR', 'Buduran', 'Sidoarjo'],
            ['CME', 'Cerme', 'Gresik'],
            ['DD', 'Duduk', 'Gresik'],
            ['GDG', 'Gedangan', 'Sidoarjo'],
            ['GEB', 'Gembong', 'Lamongan'],
            ['GNG', 'Gununggangsir', 'Pasuruan'],
            ['GS', 'Gresik', 'Gresik'],
            ['IDO', 'Indro', 'Gresik'],
            ['KDA', 'Kandangan', 'Surabaya'],
            ['KDN', 'Kedinding', 'Sidoarjo'],
            ['KGS', 'Karangkates', 'Malang'],
            ['KLM', 'Kalimas', 'Surabaya'],
            ['KMG', 'Kumendung', 'Sidoarjo'],
            ['KPN', 'Kepanjen', 'Malang'],
            ['KPS', 'Kapas', 'Bojonegoro'],
            ['KRN', 'Krian', 'Sidoarjo'],
            ['KRU', 'Kruwul', 'Lamongan'],
            ['KSB', 'Kesamben', 'Blitar'],
            ['LMG', 'Lamongan', 'Lamongan'],
            ['LW', 'Lawang', 'Malang'],
            ['ML', 'Malang', 'Malang'],
            ['MLK', 'Malangkotalama', 'Malang'],
            ['MR', 'Mojokerto', 'Mojokerto'],
            ['MST', 'Mesigit', 'Surabaya'],
            ['NB', 'Ngebruk', 'Malang'],
            ['PAD', 'Pandanan', 'Pasuruan'],
            ['PAG', 'Plampangan', 'Blitar'],
            ['PC', 'Pucuk', 'Lamongan'],
            ['PGJ', 'Pongajih', 'Blitar'],
            ['PR', 'Porong', 'Sidoarjo'],
            ['PSI', 'Pakisaji', 'Malang'],
            ['PWJ', 'Pagerwojo', 'Sidoarjo'],
            ['SB', 'Surabaya Kota', 'Surabaya'],
            ['SBI', 'Sarabaya Pasarturi', 'Surabaya'],
            ['SBN', 'Surobayan', 'Lamongan'],
            ['SBP', 'Sumberpucung', 'Malang'],
            ['SDA', 'Sidoarjo', 'Sidoarjo'],
            ['SDT', 'Sidotopo', 'Surabaya'],
            ['SGS', 'Singosari', 'Malang'],
            ['SGU', 'Surabaya Gubeng', 'Surabaya'],
            ['SKJ', 'Sukorejo', 'Pasuruan'],
            ['SLR', 'Sumlaran', 'Lamongan'],
            ['SN', 'Sengon', 'Pasuruan'],
            ['SPJ', 'Sepanjang', 'Sidoarjo'],
            ['SRJ', 'Sumberejo', 'Bojonegoro'],
            ['STM', 'Segitiga Mesigit', 'Surabaya'],
            ['STP', 'Sawotratap', 'Sidoarjo'],
            ['SYO', 'Sroyo', 'Bojonegoro'],
            ['TES', 'Tandes', 'Surabaya'],
            ['TGA', 'Tanggulangin', 'Sidoarjo'],
            ['TLN', 'Tulangan', 'Sidoarjo'],
            ['TRK', 'Tarik', 'Sidoarjo'],
            ['WG', 'Wlingi', 'Blitar'],
            ['WN', 'Wonokerto', 'Pasuruan'],
            ['WO', 'Wonokromo', 'Surabaya'],
            ['WR', 'Waru', 'Sidoarjo'],
            ['AGO', 'Argopura', 'Banyuwangi'],
            ['AJ', 'Arjoso', 'Jember'],
            ['BSS', 'Bangsalsari', 'Jember'],
            ['BW', 'Banyuwangi', 'Banyuwangi'],
            ['BWB', 'Banyuwangi Baru', 'Banyuwangi'],
            ['BWI', 'Banyuwangi Kota', 'Banyuwangi'],
            ['BYM', 'Bayeman', 'Probolinggo'],
            ['GI', 'Grati', 'Pasuruan'],
            ['GLM', 'Glenmore', 'Banyuwangi'],
            ['GRN', 'Garahan', 'Jember'],
            ['JI', 'Jati', 'Probolinggo'],
            ['JOR', 'Jorongan', 'Probolinggo'],
            ['JR', 'Jember', 'Jember'],
            ['JTR', 'Jatiroto', 'Lumajang'],
            ['KBR', 'Kalibaru', 'Banyuwangi'],
            ['KBT', 'Kabat', 'Banyuwangi'],
            ['KK', 'Klakah', 'Lumajang'],
            ['KKL', 'Krikilan', 'Banyuwangi'],
            ['KLO', 'Kaliboto', 'Lumajang'],
            ['KLT', 'Kalisat', 'Jember'],
            ['KMP', 'Kempit', 'Banyuwangi'],
            ['KNE', 'Karangasem', 'Banyuwangi'],
            ['KSL', 'Kalisetail', 'Banyuwangi'],
            ['KTG', 'Ketapang Jr', 'Banyuwangi'],
            ['KTK', 'Kotok', 'Jember'],
            ['LDO', 'Ledokombo', 'Jember'],
            ['LEC', 'Leces', 'Probolinggo'],
            ['MI', 'Mangli', 'Jember'],
            ['MLS', 'Malasan', 'Probolinggo'],
            ['MRW', 'Mrawan', 'Jember'],
            ['PB', 'Probolinggo', 'Probolinggo'],
            ['PET', 'Petung', 'Jember'],
            ['PS', 'Pasuruan', 'Pasuruan'],
            ['PS1', 'Pasuruhan', 'Pasuruan'],
            ['RBP', 'Rambipuji', 'Jember'],
            ['RDA', 'Randuagung', 'Lumajang'],
            ['RGP', 'Rogojampi', 'Banyuwangi'],
            ['RN', 'Ranuyoso', 'Lumajang'],
            ['RO', 'Rejoso', 'Pasuruan'],
            ['SBB', 'Sumberbaru', 'Jember'],
            ['SBS', 'Sumbersalak', 'Jember'],
            ['SGJ', 'Singojuruh', 'Banyuwangi'],
            ['SWD', 'Sumberwadung', 'Banyuwangi'],
            ['TGL', 'Tanggul', 'Jember'],
            ['TGR', 'Temuguruh', 'Banyuwangi'],
        ];

        foreach ($daftarStasiun as [$kode, $nama, $namaKota]) {
            $kota = Kota::where('nama', $namaKota)->first();
            if (! $kota) {
                continue;
            }
            Stasiun::firstOrCreate(
                ['kode_stasiun' => $kode],
                ['nama' => $nama, 'kota_id' => $kota->id],
            );
        }
    }
}
